<?php

namespace Database\Seeders;

use App\Models\AccountGroup;
use App\Models\Party;
use Illuminate\Database\Seeder;

class PartySeeder extends Seeder
{
    public function run(): void
    {
        $arId = AccountGroup::where('name', 'Accounts Receivable')->value('id');
        $apId = AccountGroup::where('name', 'Accounts Payable')->value('id');

        // ── Customers ────────────────────────────────────────────────────────
        $customers = [
            [
                'code'             => 'CUST-001',
                'name'             => 'Rajesh Enterprises',
                'display_name'     => 'Rajesh Ent.',
                'email'            => 'rajesh@rajeshent.com',
                'phone'            => '+91 98100 11001',
                'mobile'           => '+91 98100 11002',
                'gstin'            => '07AABCR1234A1Z5',
                'pan'              => 'AABCR1234A',
                'billing_address'  => '12, Nehru Place, New Delhi',
                'shipping_address' => '12, Nehru Place, New Delhi',
                'city'             => 'New Delhi',
                'state'            => 'Delhi',
                'country'          => 'India',
                'pincode'          => '110019',
                'opening_balance'  => 25000.00,
                'balance_type'     => 'debit',
                'credit_limit'     => '100000',
                'credit_days'      => 30,
                'account_group_id' => $arId,
            ],
            [
                'code'             => 'CUST-002',
                'name'             => 'Priya Traders Pvt. Ltd.',
                'display_name'     => 'Priya Traders',
                'email'            => 'accounts@priyatraders.in',
                'phone'            => '+91 98200 22001',
                'mobile'           => null,
                'gstin'            => '27AABCP5678B1Z3',
                'pan'              => 'AABCP5678B',
                'billing_address'  => '45, Andheri East, Mumbai',
                'shipping_address' => '45, Andheri East, Mumbai',
                'city'             => 'Mumbai',
                'state'            => 'Maharashtra',
                'country'          => 'India',
                'pincode'          => '400069',
                'opening_balance'  => 0.00,
                'balance_type'     => 'debit',
                'credit_limit'     => '200000',
                'credit_days'      => 45,
                'account_group_id' => $arId,
            ],
            [
                'code'             => 'CUST-003',
                'name'             => 'Suresh & Sons',
                'display_name'     => 'Suresh & Sons',
                'email'            => 'suresh.sons@gmail.com',
                'phone'            => '+91 94400 33001',
                'mobile'           => '+91 94400 33002',
                'gstin'            => null,
                'pan'              => 'AABCS9012C',
                'billing_address'  => '78, T. Nagar, Chennai',
                'shipping_address' => null,
                'city'             => 'Chennai',
                'state'            => 'Tamil Nadu',
                'country'          => 'India',
                'pincode'          => '600017',
                'opening_balance'  => 12500.00,
                'balance_type'     => 'debit',
                'credit_limit'     => '50000',
                'credit_days'      => 15,
                'account_group_id' => $arId,
            ],
            [
                'code'             => 'CUST-004',
                'name'             => 'Meena Retail Solutions',
                'display_name'     => 'Meena Retail',
                'email'            => 'info@meeenaretail.com',
                'phone'            => '+91 80100 44001',
                'mobile'           => null,
                'gstin'            => '29AABCM3456D1Z1',
                'pan'              => 'AABCM3456D',
                'billing_address'  => '22, MG Road, Bengaluru',
                'shipping_address' => '22, MG Road, Bengaluru',
                'city'             => 'Bengaluru',
                'state'            => 'Karnataka',
                'country'          => 'India',
                'pincode'          => '560001',
                'opening_balance'  => 0.00,
                'balance_type'     => 'debit',
                'credit_limit'     => '75000',
                'credit_days'      => 30,
                'account_group_id' => $arId,
            ],
            [
                'code'             => 'CUST-005',
                'name'             => 'Arjun Wholesale Co.',
                'display_name'     => 'Arjun Wholesale',
                'email'            => 'arjun@arjunwholesale.com',
                'phone'            => '+91 70100 55001',
                'mobile'           => '+91 70100 55003',
                'gstin'            => '36AABCA7890E1Z9',
                'pan'              => 'AABCA7890E',
                'billing_address'  => '5, Begumpet, Hyderabad',
                'shipping_address' => '5, Begumpet, Hyderabad',
                'city'             => 'Hyderabad',
                'state'            => 'Telangana',
                'country'          => 'India',
                'pincode'          => '500016',
                'opening_balance'  => 8750.00,
                'balance_type'     => 'debit',
                'credit_limit'     => '150000',
                'credit_days'      => 60,
                'account_group_id' => $arId,
            ],
        ];

        // ── Vendors ──────────────────────────────────────────────────────────
        $vendors = [
            [
                'code'             => 'VEND-001',
                'name'             => 'Global Supplies Pvt. Ltd.',
                'display_name'     => 'Global Supplies',
                'email'            => 'purchase@globalsupplies.in',
                'phone'            => '+91 11 4100 1001',
                'mobile'           => '+91 98300 10001',
                'gstin'            => '07AABCG2345F1Z2',
                'pan'              => 'AABCG2345F',
                'billing_address'  => '34, Connaught Place, New Delhi',
                'shipping_address' => null,
                'city'             => 'New Delhi',
                'state'            => 'Delhi',
                'country'          => 'India',
                'pincode'          => '110001',
                'opening_balance'  => 15000.00,
                'balance_type'     => 'credit',
                'credit_limit'     => null,
                'credit_days'      => 30,
                'account_group_id' => $apId,
            ],
            [
                'code'             => 'VEND-002',
                'name'             => 'Horizon Raw Materials',
                'display_name'     => 'Horizon RM',
                'email'            => 'billing@horizonrm.com',
                'phone'            => '+91 22 6100 2002',
                'mobile'           => null,
                'gstin'            => '27AABCH6789G1Z8',
                'pan'              => 'AABCH6789G',
                'billing_address'  => '90, MIDC, Pune',
                'shipping_address' => '90, MIDC, Pune',
                'city'             => 'Pune',
                'state'            => 'Maharashtra',
                'country'          => 'India',
                'pincode'          => '411018',
                'opening_balance'  => 0.00,
                'balance_type'     => 'credit',
                'credit_limit'     => null,
                'credit_days'      => 45,
                'account_group_id' => $apId,
            ],
            [
                'code'             => 'VEND-003',
                'name'             => 'Apex Packaging Works',
                'display_name'     => 'Apex Packaging',
                'email'            => 'apex.pkg@gmail.com',
                'phone'            => '+91 44 2100 3003',
                'mobile'           => '+91 94400 30003',
                'gstin'            => null,
                'pan'              => 'AABCA1122H',
                'billing_address'  => '15, Ambattur Industrial Estate, Chennai',
                'shipping_address' => null,
                'city'             => 'Chennai',
                'state'            => 'Tamil Nadu',
                'country'          => 'India',
                'pincode'          => '600058',
                'opening_balance'  => 5500.00,
                'balance_type'     => 'credit',
                'credit_limit'     => null,
                'credit_days'      => 15,
                'account_group_id' => $apId,
            ],
            [
                'code'             => 'VEND-004',
                'name'             => 'TechParts India Ltd.',
                'display_name'     => 'TechParts',
                'email'            => 'accounts@techparts.in',
                'phone'            => '+91 80 4100 4004',
                'mobile'           => null,
                'gstin'            => '29AABCT3344I1Z6',
                'pan'              => 'AABCT3344I',
                'billing_address'  => '67, Electronic City, Bengaluru',
                'shipping_address' => '67, Electronic City, Bengaluru',
                'city'             => 'Bengaluru',
                'state'            => 'Karnataka',
                'country'          => 'India',
                'pincode'          => '560100',
                'opening_balance'  => 0.00,
                'balance_type'     => 'credit',
                'credit_limit'     => null,
                'credit_days'      => 30,
                'account_group_id' => $apId,
            ],
            [
                'code'             => 'VEND-005',
                'name'             => 'Sunrise Logistics',
                'display_name'     => 'Sunrise Log.',
                'email'            => 'ops@sunriselogistics.com',
                'phone'            => '+91 40 2100 5005',
                'mobile'           => '+91 70100 50005',
                'gstin'            => '36AABCS5566J1Z4',
                'pan'              => 'AABCS5566J',
                'billing_address'  => '3, Jubilee Hills, Hyderabad',
                'shipping_address' => null,
                'city'             => 'Hyderabad',
                'state'            => 'Telangana',
                'country'          => 'India',
                'pincode'          => '500033',
                'opening_balance'  => 3200.00,
                'balance_type'     => 'credit',
                'credit_limit'     => null,
                'credit_days'      => 7,
                'account_group_id' => $apId,
            ],
        ];

        foreach ($customers as $data) {
            Party::create(array_merge($data, ['type' => 'customer', 'is_active' => true, 'created_by' => 1]));
        }

        foreach ($vendors as $data) {
            Party::create(array_merge($data, ['type' => 'vendor', 'is_active' => true, 'created_by' => 1]));
        }
    }
}
